title: Wracked Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.wracked.nl
params:
  disableDarkMode: true
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: Launcher
      category: Main Network
    - name: Webserver
      category: Main Network
    - category: Projects
      name: ThunderNetwork - MC server
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: white
  logo: /img/wracked_logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Main Network
      description: ""
      closed: false
      untited: true
    - name: Projects
      untited: true
      closed: false
  description: |-
    You can view the status of our services on this page.
    Keep in mind that everything is manually updated when there's an issue.
  enableCustomHTML: false
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
